Misc fixes.
Fix string conversion issue. Need to look back through qb's com methods.
```AttributeError: 'str' object has no attribute 'ProcessRequest'```